# Colors (Gruvbox dark)
# colors:
# # Default colors
# primary:
# # hard contrast: background = '#1d2021'
# background: '#1d2021'
# # soft contrast: background = '#32302f'
# foreground: '#ebdbb2'
#
# # Normal colors
# normal:
# black:   '#282828'
# red:     '#cc241d'
# green:   '#98971a'
# yellow:  '#d79921'
# blue:    '#458588'
# magenta: '#b16286'
# cyan:    '#689d6a'
# white:   '#a89984'
#
# # Bright colors
# bright:
# black:   '#928374'
# red:     '#fb4934'
# green:   '#b8bb26'
# yellow:  '#fabd2f'
# blue:    '#83a598'
# magenta: '#d3869b'
# cyan:    '#8ec07c'
# white:   '#ebdbb2'

colors:
  # Default colors
  primary:
    background: '0x282c34'
    foreground: '0xabb2bf'

  # Normal colors
  normal:
    black:   '0x1e2127'
    red:     '0xef596f'
    green:   '0x89ca78'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x2bbac5'
    white:   '0x828791'

  # Bright colors
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xe6efff'

font:
  normal:
    family: Monego Nerd Font Fix
    style: Regular

  bold:
    family: Monego Nerd Font Fix
    style: Bold

  italic:
    family: Monego Nerd Font Fix
    style: Italic

  bold_italic:
    family: Monego Nerd Font Fix
    style: Bold Italic

      # font:
      # normal:
      # family: BitstreamVeraSansMono Nerd Font Mono
      # style: Roman
      #
      # bold:
      # family: BitstreamVeraSansMono Nerd Font Mono
      # style: Bold
      #
      # italic:
      # family: BitstreamVeraSansMono Nerd Font Mono
      # style: Oblique
      #
      # bold_italic:
      # family: BitstreamVeraSansMono Nerd Font Mono
      # style: Bold Oblique

  size: 12

window:
  padding:
    x: 8
    y: 8
  decorations: transparent

# Get alt to work as expected in MacOS
key_bindings:
  - { key: N, mods: Alt, chars: "\x1bn"}
  - { key: H, mods: Alt, chars: "\x1bh"}
  - { key: J, mods: Alt, chars: "\x1bj"}
  - { key: K, mods: Alt, chars: "\x1bk"}
  - { key: L, mods: Alt, chars: "\x1bl"}
  - { key: T, mods: Alt, chars: "\x1bt"}
  - { key: 0, mods: Alt, chars: "\x1b0"}
  - { key: 1, mods: Alt, chars: "\x1b1"}
  - { key: 2, mods: Alt, chars: "\x1b2"}
  - { key: 3, mods: Alt, chars: "\x1b3"}
  - { key: 4, mods: Alt, chars: "\x1b4"}
  - { key: 5, mods: Alt, chars: "\x1b5"}
  - { key: 6, mods: Alt, chars: "\x1b6"}
  - { key: 7, mods: Alt, chars: "\x1b7"}
  - { key: 8, mods: Alt, chars: "\x1b8"}
  - { key: 9, mods: Alt, chars: "\x1b9"}

